name: cal-itp/docker-python-web

services:
  app:
    build:
      context: .
      dockerfile: appcontainer/Dockerfile
    image: cal-itp/docker-python-web:app
    entrypoint: /bin/bash
    ports:
      - "8000"
    volumes:
      - .:/home/calitp/app

  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    image: cal-itp/docker-python-web:dev
    entrypoint: sleep infinity
    ports:
      - "8000"
    volumes:
      - .:/home/calitp/app
