name: docker-python-web

services:
  app:
    build:
      context: .
      dockerfile: appcontainer/Dockerfile
    image: docker-python-web:app
    entrypoint: /bin/bash
    ports:
      - "8000"
    volumes:
      - .:/home/calitp/app

  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    image: docker-python-web:dev
    entrypoint: sleep infinity
    ports:
      - "8000"
    volumes:
      - .:/home/calitp/app

  docs:
    image: docker-python-web:dev
    entrypoint: mkdocs
    command: serve --dev-addr "0.0.0.0:8001"
    ports:
      - "8001"
    volumes:
      - .:/home/calitp/app
